### ISSUE TITLE
Aimbot doesn't lock to heads

### ISSUE THREAD

**Issue by Trixelit** [HeathHowren/CSGO-Cheats#12]
I currently have a glorified ESP as it successfully draws a line to the enemy's head, but it doesn't lock when I press alt, it doesn't actually move my cursor.

**Comment by Trixelit** [comment]
EDIT: It does set cursor, but it doesn't move in game camera. Also, the lines are not centered properly for some reason

**Comment by scriptkidde** [comment]
turn off raw input in csgo settings
